### ISSUE TITLE
System.FormatException: String '' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by Avinapster** [mattfrear/Swashbuckle.AspNetCore.Filters#143]
Dotnet : 3.1.2
Swashbuckle.AspNetCore: 5.0.0

I am getting this error. I am attaching full stack trace of the issue.

`System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.TryCast[T](Object value, T& typedValue)
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.CreateFor(OpenApiSchema schema, Object value)
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiSchemaExtensions.ApplyCustomAttributes(OpenApiSchema schema, IEnumerable`1 customAttributes)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreatePropertySchema(JsonProperty jsonProperty, IEnumerable`1 customAttributes, Required required, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreatePropertySchema(JsonProperty jsonProperty, IEnumerable`1 customAttributes, Required required, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreatePropertySchema(JsonProperty jsonProperty, IEnumerable`1 customAttributes, Required required, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftArrayHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreatePropertySchema(JsonProperty jsonProperty, IEnumerable`1 customAttributes, Required required, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreatePropertySchema(JsonProperty jsonProperty, IEnumerable`1 customAttributes, Required required, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateObjectSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftArrayHandler.CreateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass18_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 342.2397ms 500`

**Comment by mattfrear** [comment]
I think you have posted this issue in the wrong GitHub project.
This project is Swashbuckle.AspNetCore.Filters - are you using that?

Swashbuckle.AspNetCore is a different GitHub project.
