### ISSUE TITLE
OpenAPI.NET 1.2.0 broke OpenApiString

### ISSUE THREAD

**Issue by CumpsD** [mattfrear/Swashbuckle.AspNetCore.Filters#154]
https://github.com/microsoft/OpenAPI.NET/issues/487

NuGet decided to install 1.2.0 in a project of mine which caused `System.MissingMethodException: Method not found: 'Void Microsoft.OpenApi.Any.OpenApiString..ctor(System.String)'.`

```
System.MissingMethodException: Method not found: 'Void Microsoft.OpenApi.Any.OpenApiString..ctor(System.String)'.
   at Swashbuckle.AspNetCore.Filters.ExamplesConverter.SerializeExampleXml(Object exampleValue)
   at Swashbuckle.AspNetCore.Filters.RequestExample.<>c__DisplayClass6_0.<SetSingleRequestExampleForOperation>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Swashbuckle.AspNetCore.Filters.RequestExample.SetSingleRequestExampleForOperation(OpenApiOperation operation, Object example, ExamplesConverter examplesConverter)
   at Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, Object example, IContractResolver contractResolver, JsonConverter jsonConverter)
   at Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter.SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
```

We need to upgrade to 1.2.0 to fix this, I'll make a PR later today

**Comment by nixxholas** [comment]
+1 to this. My production web app failed..

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.1.2
