### ISSUE TITLE
swagger started to throw exception that there is no xml output formatter, which I don't need, but after adding it all responses become in xml

### ISSUE THREAD

**Issue by KittKillward** [mattfrear/Swashbuckle.AspNetCore.Filters#238]
On a project all api uses mostly jsons for requests and responses. Sometimes it is just a string.

Swagger has already been used in the project and worked well, but there is a need to write several examples for requests. So I added this library.

After adding and installing this library, when in project exists class with examples that inherits from IExamplesProvider<T> swagger throws in console exception that it needs xml output formatter and does not load. Even though project does not need xml formatter at all
```
---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - ChatBotConstructor.Controllers.ContainerSettings.ContainerSettingsController.GetContainer (ChatBotConstructor). See inner exception
       ---> Swashbuckle.AspNetCore.Filters.MvcOutputFormatter+FormatterNotFoundException: OutputFormatter not found for 'application/xml; charset=utf-8'
         at Swashbuckle.AspNetCore.Filters.MvcOutputFormatter.Serialize[T](T value, MediaTypeHeaderValue contentType)
         at Swashbuckle.AspNetCore.Filters.ExamplesConverter.SerializeExampleXml(Object value)
         at Swashbuckle.AspNetCore.Filters.RequestExample.<>c__DisplayClass4_0.<SetSingleRequestExampleForOperation>b__1()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Swashbuckle.AspNetCore.Filters.RequestExample.SetSingleRequestExampleForOperation(OpenApiOperation operation, Object example, ExamplesConverter examplesConverter)
         at Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestBodyExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, Object example)
         at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
         at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
         --- End of inner exception stack trace ---
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/81771227/80b3ae65-404c-4583-80f1-bc20a7cb3d88)

When I add the formatter then this error disappear. But then swagger shows responses only in xml for all api, no matter what am I doing or configuring.

Only when I add [Produces("application/json")] attribute responses returns back to json. But adding this attribute on hundreds of api when I don't need xml at all doesn't look right.

**so how can I use this library without adding xml formatter?**

I configuring swagger like this:
```
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "AppName", Version = "v1" });

    c.ExampleFilters();

    var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    c.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, xmlFilename));

    c.EnableAnnotations();
        
    OpenApiSecurityScheme securityDefinition = new OpenApiSecurityScheme()
    {
        Name = "Bearer",
        BearerFormat = "JWT",
        Scheme = "bearer",
        Description = "Specify the authorization token.",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
    };

    OpenApiSecurityRequirement securityRequirements = new OpenApiSecurityRequirement()
    {
        {securityDefinition, Array.Empty<String>()},
    };
        
    c.AddSecurityDefinition("jwt_auth", securityDefinition);
    c.AddSecurityRequirement(securityRequirements);
});
services.AddSwaggerExamplesFromAssemblyOf<Startup>();
services.AddSwaggerExamplesFromAssemblyOf<RequestPayload>();
```
```
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "AppName v1"));
```

and MvcBuilder like this:
```
var mvcBuilder = services.AddControllers(o =>
{
    o.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true;
    o.Filters.Add(new AuthorizeFilter());
    o.AllowEmptyInputInBodyModelBinding = true;
    //o.RespectBrowserAcceptHeader = true; // this does not help with the next line
    //o.OutputFormatters.Insert(0, new XmlSerializerOutputFormatter()); // after adding this all responses in swagger become in xml
})
.AddApplicationPart(assemblyMarker)
.AddControllersAsServices()
.AddBatchQuery(modelBuilder)
.AddJsonOptions(options =>
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()))
.AddNewtonsoftJson();
``` 

My model and example for this model:
```
public class SortPaginationPartialPayload
{
    public PaginationInfo Pagination { get; set; }

    public SortInfo Sort { get; set; }
}
#region swagger examples
public class ContainerSettingsGetContainerExample : IExamplesProvider<SortPaginationPartialPayload>
{
    public SortPaginationPartialPayload GetExamples()
    {
        var sortPaginationPartialPayload = new SortPaginationPartialPayload()
        {
            Pagination = new PaginationInfo
            {
                TypePagination = TypePaginationEnum.InfiniteScroll,
                Offset = 0,
                Limit = 100,
                CurrentPage = null,
                MaxPerPage = null
            },
            Sort = new SortInfo
            {
                TypeSorting = TypeSortingEnum.Desc,
                ColumnName = nameof(Container.CreateDate)
            }
        };
        return sortPaginationPartialPayload;
    }
}
#endregion
```

example on api method I'm using like this:
```
/// xml summary, remarks, description of status codes and description with example of url parameter 
[HttpPost(nameof(GetContainer))]
[ProducesResponseType(typeof(InfiniteScrollResponseModel<ContainerSettingsModel>), StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status204NoContent)]
[ProducesResponseType(typeof(DefaultApiErrorResponse), StatusCodes.Status500InternalServerError)]
[SwaggerRequestExample(typeof(SortPaginationPartialPayload), typeof(ContainerSettingsGetContainerExample))]
//[Produces("application/json")] //only with attribute api returns back to normal json after I add xml formatter to fix exception
public async Task<ActionResult<List<ContainerSettingsModel>?>> GetContainer(
    [FromQuery] Guid? containerId,
    [FromBody] SortPaginationPartialPayload? sortPaginationInfo)
{
//...
}
```

**Comment by KittKillward** [comment]
Solution was founded. 

It seems like after adding filters library swagger starts hardly depending from xml formatter and you can't go anywhere without it. 

And among json and xml formatters the one that was added first is set by default.

in my example, the xml formatter was installed first through option of AddControllers() and then Newtonsoft json formatter was installed by calling AddNewtonsoftJson() on MvcBuilder.

So I found in some github examples of this library that xml formatter may also be installed on MvcBuilder.
I add xml formatter like this
```
.AddNewtonsoftJson().AddXmlDataContractSerializerFormatters();
```
and now don't have exceptions and have everywhere jsons by default.

**Comment by mattfrear** [comment]
Hmm, this sounds like it needs further investigation.

I'm surprised that 6 people have given it a thumbs up, even though you only opened the issue 9 hours ago - do you know them?

**Comment by KittKillward** [comment]
> I'm surprised that 6 people have given it a thumbs up, even though you only opened the issue 9 hours ago - do you know them?
Yes, I know them 😅
