### ISSUE TITLE
How to get examle value from XML comment work with source generation based JSON serialization?

### ISSUE THREAD

**Issue by hackerzhuli** [mattfrear/Swashbuckle.AspNetCore.Filters#252]
Hello, I can't get example value in XML comment to work in Swagger with this library. My project is an Web API based on Asp.net Core, Native AOT, .net 8 and Minimal API. JSON serializaion is source generation based.

Here are my packages:
``` xml
<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2" />
```

Here is my config code:

``` cs
// relevant swagger config
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.ExampleFilters();
    
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
    
    c.OperationFilter<AppendAuthorizeToSummaryOperationFilter>(); // Adds "(Auth)" to the summary so that you can see which endpoints have Authorization
});

builder.Services.AddSwaggerExamplesFromAssemblies(Assembly.GetEntryAssembly());

// this is serialization related code
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
});

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(MyTypeA))]
[JsonSerializable(typeof(MyTypeB))]
[JsonSerializable(typeof(MyTypeC))]
// ... and many more custom types for request and response (DTO)
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
```

The XML comment is working well (show up in Swagger pages) if I don't use example attribute. However, when I add example attribute in XML comment, there is an exception, related to serialization.

Here is my problem XML comment:
``` cs
    /// <summary>
    /// upload build
    /// </summary>
    /// <param name="file">file</param>
    /// <param name="app" example="one">app id</param>
    public static async Task<Results<Ok<UploadOut>, ValidationProblem>> Upload(IFormFile? file, string? app)
    {
        // implementation skipped
    }
```

If I delete `example="one", Swagger works. But with it in XML comment, I get an exception:
``` txt
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Build. See inner exception
       ---> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
         at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
         at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
         at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
         at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
         at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsExampleHelper.Create(SchemaRepository schemaRepository, OpenApiSchema schema, String exampleString)
         at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsParameterFilter.ApplyParamTags(OpenApiParameter parameter, ParameterFilterContext context)
         at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsParameterFilter.Apply(OpenApiParameter parameter, ParameterFilterContext context)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass16_0.<GenerateParameters>b__1(ApiParameterDescription apiParam)
         at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
```

**Comment by hackerzhuli** [comment]
Closed due to issue belongs to Swashbuckle.AspNetCore, not this library.
