### ISSUE TITLE
Exception when using ExampleFilters

### ISSUE THREAD

**Issue by veler** [mattfrear/Swashbuckle.AspNetCore.Filters#56]
Hi :)

I'm facing an exception when I'm using `o.ExampleFilters()`.

This is the partial configuration code I have : 

```
opt.ExampleFilters();
services.AddSwaggerExamples();

opt.OperationFilter<AddRequiredHeaderParameter>();
opt.OperationFilter<AddResponseHeadersFilter>();
opt.OperationFilter<DescriptionOperationFilter>();
opt.OperationFilter<AddFileParamTypesOperationFilter>();
opt.OperationFilter<AddResponseHeadersFilter>();
opt.DescribeAllEnumsAsStrings();
opt.DescribeAllParametersInCamelCase();
```

And this is the exception :

```
Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Swashbuckle.AspNetCore.Filters.RequestExample' while attempting to activate 'Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter'.

   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass35_0`1.<CreateFilters>b__0(FilterDescriptor`1 descriptor)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerGeneratorSettings(IServiceProvider serviceProvider)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Unable to resolve service for type 'Swashbuckle.AspNetCore.Filters.RequestExample' while attempting to activate 'Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass35_0`1.<CreateFilters>b__0(FilterDescriptor`1 descriptor)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerGeneratorSettings(IServiceProvider serviceProvider)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

We're using `ASP.Net Core 2.0`

Thanks in advance =)

**Comment by mattfrear** [comment]
You need to call `services.AddSwaggerExamples();` outside of the `AddSwaggerGen` call, as shown on the Readme. I will update the readme to make this even clearer.
